/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-18 17:04:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import bean.Pelicula;
import java.util.List;
import bean.Pelicula;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/header.jsp", Long.valueOf(1676737912577L));
    _jspx_dependants.put("/WEB-INF/peliculas.jsp", Long.valueOf(1676739867710L));
    _jspx_dependants.put("/WEB-INF/cine.jsp", Long.valueOf(1676562946732L));
    _jspx_dependants.put("/WEB-INF/footer.jsp", Long.valueOf(1676231819031L));
    _jspx_dependants.put("/WEB-INF/pelicula.jsp", Long.valueOf(1676733569726L));
    _jspx_dependants.put("/WEB-INF/cines.jsp", Long.valueOf(1676310031074L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.Pelicula");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"utf-8\">\r\n");
      out.write("		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("		<meta name=\"description\" content=\"Multicines Cinestar es una empresa pionera en el formato de multicines en el Perú. Información de películas, estrenos, concursos y más\">\r\n");
      out.write("		<link rel=\"shortcut icon\" href=\"img/varios/favicon.ico\">\r\n");
      out.write("		<link href=\"css/estilos.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("		<title>Multicines Cinestar</title>\r\n");
      out.write("	</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<body>\r\n");
      out.write("		<header>\r\n");
      out.write("			<nav class=\"nav-sec\">\r\n");
      out.write("        		<a href=\"index.jsp\">Inicio</a>&nbsp;&nbsp;l&nbsp;&nbsp;\r\n");
      out.write("        		<a href=\"http://www.cinestar.com.pe/quienes_somos\">Quiénes somos</a>&nbsp;&nbsp;l&nbsp;&nbsp;\r\n");
      out.write("        		<a href=\"http://www.cinestar.com.pe/trabaja_con_nosotros\">Trabaja con nosotros</a>&nbsp;&nbsp;l&nbsp;&nbsp;\r\n");
      out.write("        		<a href=\"https://www.efact.pe/consult.html\" target=\"_blank\">Consulta tu comprobante de pago </a>&nbsp;&nbsp;l&nbsp;&nbsp;\r\n");
      out.write("        		<a href=\"http://www.cinestar.com.pe/contactenos/#contenido_titulo\" class=\"anchorLink\">Contáctenos</a>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"area-logo\">\r\n");
      out.write("				<a href=\"index.jsp\"><img src=\"img/varios/logo-cinestar.png\"/></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<nav class=\"menu\">\r\n");
      out.write("				<span class=\"img-social\">\r\n");
      out.write("					<a href=\"http://www.facebook.com/multicinestar\" target=\"_blank\"><img src=\"img/varios/ico-face.png\"/></a>\r\n");
      out.write("					<a href=\"http://www.twitter.com/multicinestar\" target=\"_blank\"><img src=\"img/varios/ico-twitter.png\"/></a>\r\n");
      out.write("				</span>\r\n");
      out.write("				<span class=\"social\">Síguenos en: </span>\r\n");
      out.write("				<ul class=\"menu-principal\">\r\n");
      out.write("		    		<li class=\"menu-item\"><a href=\"SvlPelicula?id=cartelera\">Cartelera</a></li>\r\n");
      out.write("		       		<li class=\"menu-item\"><a href=\"SvlPelicula?id=estrenos\">Próximos estrenos</a></li>\r\n");
      out.write("		       		<li class=\"menu-item\"><a href=\"http://www.cinestar.com.pe/starcard\">Star Card</a></li>\r\n");
      out.write("		        	<li class=\"menu-item\"><a href=\"svlCine\">Nuestros Cines</a></li>\r\n");
      out.write("		        	<li class=\"menu-item\"><a href=\"http://www.cinestar.com.pe/ventas_corporativas\">Ventas Corporativas</a></li>\r\n");
      out.write("		        	<li class=\"menu-item\"><a href=\"http://www.cinestar.com.pe/promociones\">Promociones</a></li>\r\n");
      out.write("		        	<li class=\"menu-item\"><a href=\"http://www.cinestar.com.pe/cinefilo_star\">Blog</a></li>\r\n");
      out.write("		    	</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"slider\">\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"papaya\">\r\n");
      out.write("				<a href=\"http://www.cinepapaya.com/pe/cinestar\" target=\"_blank\"><img src=\"img/varios/bg-papaya.jpg\"/></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"contenido\">\r\n");
      out.write("			<div class=\"publicidad\">\r\n");
      out.write("				<a href=\"http://www.cinestar.com.pe/starcard/\"><img src=\"img/varios/starcard.jpg\"/></a>\r\n");
      out.write("				<a href=\"http://www.cinestar.com.pe/cinefilo_star/\"><img src=\"img/varios/cinefilo-star.jpg\"/></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"contenido-interno\" id=\"contenido-interno\">\r\n");
      out.write("				");
  Object id = session.getAttribute("id");
					if (id == null) { 
      out.write(" \r\n");
      out.write("					");
 } else if (id.equals("peliculas") ) { 
      out.write("\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("	<body>\r\n");
      out.write("		<br/><h1>Cartelera</h1><br/>\r\n");
      out.write("		");

		List <Pelicula> peliculas = (List <Pelicula>) session.getAttribute("data");
		for (Pelicula pelicula: peliculas){ 
      out.write("\r\n");
      out.write("				<div class=\"contenido-pelicula\">\r\n");
      out.write("					<div class=\"datos-pelicula\">\r\n");
      out.write("						<h2>");
      out.print( pelicula.getTitulo() );
      out.write("</h2><br/>\r\n");
      out.write("						<p>");
      out.print( pelicula.getSinopsis() );
      out.write("</p>\r\n");
      out.write("						<br/>\r\n");
      out.write("                       	<div class=\"boton-pelicula\"> \r\n");
      out.write("                       		<a href=\"SvlPelicula?id=");
      out.print( pelicula.getId() );
      out.write("\" >\r\n");
      out.write("                       			<img src=\"img/varios/btn-mas-info.jpg\" width=\"120\" height=\"30\" alt=\"Ver info\"/>\r\n");
      out.write("                       		</a>\r\n");
      out.write("               			</div>\r\n");
      out.write("               			<div class=\"boton-pelicula\"> \r\n");
      out.write("               				<a href=\"http://www.cinestar.com.pe/popups/trailer/");
      out.print( pelicula.getLink() );
      out.write("\" onclick=\"return hs.htmlExpand(this, { objectType: 'iframe' } )\" >\r\n");
      out.write("               					<img src=\"img/varios/btn-trailer.jpg\" width=\"120\" height=\"30\" alt=\"Ver trailer\"/>\r\n");
      out.write("               				</a>\r\n");
      out.write("                        </div> \r\n");
      out.write("					</div>\r\n");
      out.write("					<img src=\"img/pelicula/");
      out.print( pelicula.getId() );
      out.write(".jpg\" width=\"160\" height=\"226\"/><br/><br/>\r\n");
      out.write("				</div>\r\n");
      out.write("			");
 }
      out.write("	\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("					");
 } else if (id.equals("pelicula") ) { 
      out.write("\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<body>\r\n");
      out.write("	");
 Pelicula pelicula = (Pelicula) session.getAttribute("data");
      out.write("\r\n");
      out.write("		<br/><h1>Cartelera</h1><br/>\r\n");
      out.write("				<div class=\"contenido-pelicula\">\r\n");
      out.write("					<div class=\"datos-pelicula\">\r\n");
      out.write("						<h2>");
      out.print( pelicula.getTitulo() );
      out.write("</h2>\r\n");
      out.write("						<p>");
      out.print( pelicula.getSinopsis() );
      out.write("</p>\r\n");
      out.write("						<br/>\r\n");
      out.write("						<div class=\"tabla\">\r\n");
      out.write("							<div class=\"fila\">\r\n");
      out.write("								<div class=\"celda-titulo\">Titulo Original :</div>\r\n");
      out.write("								<div class=\"celda\">");
      out.print( pelicula.getTitulo() );
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"fila\">\r\n");
      out.write("								<div class=\"celda-titulo\">Estreno :</div>\r\n");
      out.write("								<div class=\"celda\">");
      out.print( pelicula.getFechaEstreno() );
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"fila\">\r\n");
      out.write("								<div class=\"celda-titulo\">Genero :</div>\r\n");
      out.write("								<div class=\"celda\">");
      out.print( pelicula.getGeneros() );
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"fila\">\r\n");
      out.write("								<div class=\"celda-titulo\">Director :</div>\r\n");
      out.write("								<div class=\"celda\">");
      out.print( pelicula.getDirector() );
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"fila\">\r\n");
      out.write("								<div class=\"celda-titulo\">Reparto :</div>\r\n");
      out.write("								<div class=\"celda\">");
      out.print( pelicula.getReparto() );
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<img src=\"img/pelicula/");
      out.print( pelicula.getId() );
      out.write(".jpg\" width=\"160\" height=\"226\"><br/><br/>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"pelicula-video\">\r\n");
      out.write("					<embed src=\"http://www.youtube.com/v/");
      out.print( pelicula.getLink() );
      out.write("\" type=\"application/x-shockwave-flash\" =\"always\" allowfullscreen=\"true\" width=\"580\" height=\"400\">\r\n");
      out.write("				</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("S\r\n");
      out.write("					");
 } else if (id == "4" ) { 
      out.write("\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<body>\r\n");
      out.write("		<br/><h1>Nuestros Cines</h1><br/>\r\n");
      out.write("		");

		String [][] mCines = (String [][]) session.getAttribute("mCines");
		for (String []aCine : mCines){ 
      out.write("\r\n");
      out.write("				<div class=\"contenido-cine\">\r\n");
      out.write("	        	    <img src=\"img/cine/");
      out.print( aCine[0] );
      out.write(".1.jpg\" width=\"227\" height=\"170\"/>\r\n");
      out.write("            	   	<div class=\"datos-cine\">\r\n");
      out.write("       				   	<h4>");
      out.print( aCine[1]);
      out.write("</h4><br/>\r\n");
      out.write("                		<span>");
      out.print( aCine[4]);
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( aCine[6]);
      out.write("<br/><br/>Teléfono: ");
      out.print( aCine[5]);
      out.write("</span>\r\n");
      out.write("                	</div>\r\n");
      out.write("                	<br/>\r\n");
      out.write("                	<a href=\"svlCine?idCine=");
      out.print( aCine[0]);
      out.write("\">\r\n");
      out.write("                		<img src=\"img/varios/ico-info2.png\" width=\"150\" height=\"40\"/>\r\n");
      out.write("                	</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			");
 }
      out.write("	\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("					");
 } else if (id == "5" ) { 
      out.write("\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<body>\r\n");
      out.write("		");
 String [] aCine = (String []) session.getAttribute("aCine");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<h2>");
      out.print( aCine[1] );
      out.write("</h2>\r\n");
      out.write("				<div class=\"cine-info\">\r\n");
      out.write("					<div class=\"cine-info datos\">\r\n");
      out.write("						<p>");
      out.print( aCine[4] );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( aCine[6] );
      out.write("</p>\r\n");
      out.write("						<p>Teléfono: ");
      out.print( aCine[5] );
      out.write("</p>\r\n");
      out.write("						<br/>\r\n");
      out.write("						<div class=\"tabla\">\r\n");
      out.write("						");
 String [][] mTarifas = (String [][]) session.getAttribute("mTarifas");
							boolean bolFila=true;
							for (String [] aTarifa:mTarifas) { 
      out.write("\r\n");
      out.write("							<div class=");
      out.print( bolFila ? "fila" : "fila impar" );
      out.write(">\r\n");
      out.write("								<div class=\"celda-titulo\">");
      out.print( aTarifa[0] );
      out.write("</div>\r\n");
      out.write("								<div class=\"celda\">");
      out.print( aTarifa[1] );
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						 ");
 bolFila= !bolFila; } 
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"aviso\">\r\n");
      out.write("							<p>A partir del 1ro de julio de 2016, Cinestar Multicines realizará el cobro de la comisión de S/. 1.00 adicional al tarifario vigente, a los usuarios que compren sus entradas por el aplicativo de Cine Papaya para Cine Star Comas, Excelsior, Las Américas, Benavides, Breña, San Juan, UNI, Aviación, Sur, Porteño, Tumbes y Tacna.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<img src=\"img/cine/1.2.jpg\"/>\r\n");
      out.write("					<br/><br/><h4>Los horarios de cada función están sujetos a cambios sin previo aviso.</h4><br/>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"cine-info peliculas\">\r\n");
      out.write("						<div class=\"tabla\">\r\n");
      out.write("							<div class=\"fila\">\r\n");
      out.write("								<div class=\"celda-cabecera\">Películas</div>\r\n");
      out.write("								<div class=\"celda-cabecera\">Horarios</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							");
 String [][] mPeliculas = (String [][]) session.getAttribute("mPeliculas");
								bolFila=false;
								for (String [] aPelicula:mPeliculas) { 
      out.write("\r\n");
      out.write("							<div class=");
      out.print( bolFila ? "fila" : "fila impar" );
      out.write(">\r\n");
      out.write("								<div class=\"celda-titulo\">");
      out.print( aPelicula[0] );
      out.write("</div>\r\n");
      out.write("								<div class=\"celda\">");
      out.print( aPelicula[1] );
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							");
 bolFila= !bolFila; } 
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<img style=\"float:left;\" src=\"img/cine/");
      out.print( aCine[0] );
      out.write(".3.jpg\"/>\r\n");
      out.write("					<span class=\"tx_gris\">Precios de los juegos: desde S/1.00 en todos los Cine Star.<br/>\r\n");
      out.write("						Horario de atención de juegos es de 12:00 m hasta las 10:30 pm. \r\n");
      out.write("						<br/><br/>\r\n");
      out.write("						Visitános y diviértete con nosotros. \r\n");
      out.write("						<br/><br/>\r\n");
      out.write("						<b>CINESTAR</b>, siempre pensando en tí. \r\n");
      out.write("					</span>\r\n");
      out.write("				</div>	\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"clearbox\"><br/></div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<body>\r\n");
      out.write("		<footer>\r\n");
      out.write("			<div class=\"contenido-footer\">\r\n");
      out.write("				<p>Copyright © 2016 ® Multicines CINESTAR - Todos los Derechos Reservados</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
