/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-03-12 20:26:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class actas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/header.jsp", Long.valueOf(1677336933416L));
    _jspx_dependants.put("/WEB-INF/footer.jsp", Long.valueOf(1677244400229L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
	String nroMesa = (String) session.getAttribute("nroMesa");
	String[][] data = (String[][]) session.getAttribute("data");
	

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html> \r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("        <title>ONPE - Oficina Nacional de Procesos Electorales</title>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"  /> \r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\" />\r\n");
      out.write("        <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("        <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"/>		\r\n");
      out.write("    </head>\r\n");
      out.write("	<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"pull-left logo-onpe\">\r\n");
      out.write("            <div class=\"pull-left\"><a href=\"index.jsp\"><img src=\"images/onpe-trans.png\"></a></div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"pull-left\">\r\n");
      out.write("                <h1>PRESENTACIÓN DE RESULTADOS</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"pull-right logo\">\r\n");
      out.write("            <img src=\"images/eegg2016-trans.png\" width=\"218\" height=\"35\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <img src=\"images/fnd-actas.jpg\" width=\"1170\" height=\"248\" class=\"img-responsive mg30top\">\r\n");
      out.write("\r\n");
      out.write("            <section class=\"menu navbar-default menu05\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button class=\"navbar-toggle collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\".bs-navbar-collapse\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("				<a name=\"posicion\"></a>\r\n");
      out.write("                <nav class=\"navbar-collapse bs-navbar-collapse collapse\" aria-expanded=\"false\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav\">\r\n");
      out.write("                        <li class=\"bt-azul\">\r\n");
      out.write("                            <a href=\"presidenciales.jsp\">PRESIDENCIAL</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"bt-amarillo act-amarillo\">\r\n");
      out.write("                            <a href=\"svlActas\">ACTAS</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"bt-rojo\">\r\n");
      out.write("                            <a href=\"svlParticipacion\">PARTICIPACIÓN CIUDADANA</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("                       <section class=\"contenedor\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-12 col-md-3 mg20top\">\r\n");
      out.write("                        <div class=\"menu-interna\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"svlActas\">Actas por ubigeo</a></li>\r\n");
      out.write("                                <li><a href=\"svlActas\" class=\"act-izq\">Actas por número</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-11 col-md-9\" id=\"impreso\">\r\n");
      out.write("                        <div class=\"contenido-interna mg20top\">\r\n");
      out.write("                            <div class=\"titulos col-xs-12\">\r\n");
      out.write("                                <div class=\"col-xs-11\">\r\n");
      out.write("                                    <h3> <span class=\"glyphicon glyphicon-circle-arrow-right\" aria-hidden=\"true\" style=\"font-size:19px\"></span> SEGUNDA ELECCIÓN PRESIDENCIAL 2016: ACTAS POR NÚMERO</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-xs-1 oculto-boton-print\">\r\n");
      out.write("                                    <button onclick=\"printContent('impreso');\"><i class=\"fa fa-print ico-print\"></i></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-xs-12\">\r\n");
      out.write("							\r\n");
      out.write("                                	<div class=\"col-lg-8 centered\">\r\n");
      out.write("							<div class=\"col-xs-12 col-md-12 col-lg-12 cont-curv\">\r\n");
      out.write("								<div class=\"col-xs-3 col-md-1\">\r\n");
      out.write("									<span class=\"glyphicon glyphicon-ok-circle ico-info\" aria-hidden=\"true\"></span>\r\n");
      out.write("								</div>\r\n");
      out.write("					\r\n");
      out.write("								<div class=\"col-xs-9 col-md-11 mg20top\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>ACTUALIZADO EL  \r\n");
      out.write("                                            <script languaje=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("                                                var mydate=new Date()\r\n");
      out.write("                                                var year=mydate.getYear()\r\n");
      out.write("                                                if (year < 1000)\r\n");
      out.write("                                                year+=1900\r\n");
      out.write("                                                var day=mydate.getDay()\r\n");
      out.write("                                                var month=mydate.getMonth()\r\n");
      out.write("                                                var daym = mydate.getDate()\r\n");
      out.write("                                                var hora = mydate.getHours()\r\n");
      out.write("                                                var minutos = mydate.getMinutes()\r\n");
      out.write("                                                if (daym<10)\r\n");
      out.write("                                                daym=\"0\"+daym\r\n");
      out.write("                                                var montharray=new\r\n");
      out.write("\r\n");
      out.write("                                                Array(\"ENERO\",\"FEBREO\",\"MARZO\",\"ABRILl\",\"MAYO\",\"JUNIO\",\"JULIO\",\"AGOSTO\",\"SEPTIEMBRE\",\"OCTUBRE\",\"NOVIEMBRE\",\"DICIEMBRE\")\r\n");
      out.write("                                                document.write(daym+ \" DE \"+montharray[month]+\" \"+year+ \" A LAS \"+hora+\":\"+minutos+\" h\")\r\n");
      out.write("\r\n");
      out.write("                                            </script>\r\n");
      out.write("                                        </li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"page-wrap\">\r\n");
      out.write("									<br>\r\n");
      out.write("									<p>&nbsp;</p>\r\n");
      out.write("									<p>&nbsp;</p>\r\n");
      out.write("									\r\n");
      out.write("								    <form id=\"myform\"  method=\"post\" \">\r\n");
      out.write("											<div class=\"col-md-3\">\r\n");
      out.write("												INGRESE EL NÚMERO DE ACTA:\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"col-md-4\">\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													<span id=\"spanNroMesa\">\r\n");
      out.write("														<input id=\"nroMesa\" name=\"nroMesa\" type=\"text\" onKeyPress=\"return validText(this, event, 4)\" maxlength=\"6\" class=\"form-control\" value=\"\"/>\r\n");
      out.write("													</span>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"col-md-2\">\r\n");
      out.write("												<button type=\"button\" \r\n");
      out.write("												onclick=\"fuction recibir();\"\r\n");
      out.write("												class=\"btn btn-primary\"><span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span> BUSCAR</button>\r\n");
      out.write("											</div>\r\n");
      out.write("										\r\n");
      out.write("									</form>\r\n");
      out.write("									<script type=\"text/avaScript\">\r\n");
      out.write("										fuction recibir(){\r\n");
      out.write("											var nroMesa = document.getElementById(\"nroMesa\").value\r\n");
      out.write("										}\r\n");
      out.write("                                    </script>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            <br></br>\r\n");
      out.write("                            <div id=\"divDetalle\" class=\"ptop20\">\r\n");
      out.write("                            ");
 if (  nroMesa != null && data != null ) { 
      out.write("\r\n");
      out.write("                            <div class=\"contenido-resultados\">\r\n");
      out.write("		            		<p>&nbsp;</p>\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"tab-info\">\r\n");
      out.write("										<div class=\"tab-content\">\r\n");
      out.write("											<div id=\"detMesa\">\r\n");
      out.write("													<div class=\"tab-content\">\r\n");
      out.write("													<div role=\"tabpanel\" class=\"tab-pane active\" id=\"presidencial\">\r\n");
      out.write("														<div class=\"tab-info-desc\">\r\n");
      out.write("															<div class=\"row\">\r\n");
      out.write("																<div class=\"col-xs-3 col-md-4\">\r\n");
      out.write("																	<div class=\"mesap01\">\r\n");
      out.write("																		<img src=\"images/mp-sin.jpg\" class=\"img-responsive\">\r\n");
      out.write("																	Si requiere la imagen del acta, solicítela a través del procedimiento de acceso a la información pública.\r\n");
      out.write("																	</div>\r\n");
      out.write("																</div>\r\n");
      out.write("													<div class=\"col-xs-9 col-md-8\">\r\n");
      out.write("														<div class=\"row\">\r\n");
      out.write("															<div class=\"col-xs-12\">\r\n");
      out.write("																<p class=\"subtitle1\">ACTA ELECTORAL</p>\r\n");
      out.write("																<div id=\"page-wrap\">\r\n");
      out.write("																");
 for ( String[] aData : data ) { 
      out.write("    \r\n");
      out.write("																	<table class=\"table13\" cellspacing=\"0\">\r\n");
      out.write("																		<thead>\r\n");
      out.write("																			<tr>\r\n");
      out.write("																				<th>Mesa N°</th>\r\n");
      out.write("																				<th>N° Copia</th>\r\n");
      out.write("																			</tr>\r\n");
      out.write("																		</thead>\r\n");
      out.write("																		<tbody>\r\n");
      out.write("																			<tr>\r\n");
      out.write("																				<td>");
      out.print( aData[6] );
      out.write("</td>\r\n");
      out.write("																				<td>\r\n");
      out.write("																					");
      out.print( aData[7] );
      out.write("\r\n");
      out.write("																				</td>\r\n");
      out.write("																			</tr>\r\n");
      out.write("																		</tbody>\r\n");
      out.write("																	</table>\r\n");
      out.write("																</div>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("														<div class=\"col-xs-12\">\r\n");
      out.write("															<p class=\"subtitle1\">INFORMACIÓN UBIGEO</p>\r\n");
      out.write("															<div id=\"page-wrap\">\r\n");
      out.write("																<table class=\"table14\" cellspacing=\"0\">\r\n");
      out.write("																	<tbody>\r\n");
      out.write("																		<tr class=\"titulo_tabla\">\r\n");
      out.write("																			<td>Departamento</td>\r\n");
      out.write("																			<td>Provincia</td>\r\n");
      out.write("																			<td>Distrito</td>\r\n");
      out.write("																			<td>Local de votación</td>\r\n");
      out.write("																			<td>Dirección</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<td>");
      out.print( aData[0] );
      out.write("</td>\r\n");
      out.write("																			<td>");
      out.print( aData[1] );
      out.write("</td>\r\n");
      out.write("																			<td>");
      out.print( aData[2] );
      out.write("</td>\r\n");
      out.write("																			<td>");
      out.print( aData[3] );
      out.write("</td>\r\n");
      out.write("																			<td>");
      out.print( aData[4] );
      out.write("</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																	</tbody>\r\n");
      out.write("																</table>\r\n");
      out.write("															</div>\r\n");
      out.write("														</div>\r\n");
      out.write("\r\n");
      out.write("														<div class=\"col-xs-12\">\r\n");
      out.write("															<p class=\"subtitle1\">INFORMACIÓN MESA</p>\r\n");
      out.write("															<div id=\"page-wrap\">\r\n");
      out.write("																<table class=\"table15\" cellspacing=\"0\">\r\n");
      out.write("																	<tbody>\r\n");
      out.write("																		<tr class=\"titulo_tabla\">\r\n");
      out.write("																			<td>Electores hábiles</td>\r\n");
      out.write("																			<td>Total votantes</td>\r\n");
      out.write("																			<td>Estado del acta</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		<tr>\r\n");
      out.write("																			<td>");
      out.print( aData[9] );
      out.write("</td>\r\n");
      out.write("																			<td>");
      out.print( aData[10] );
      out.write("</td>\r\n");
      out.write("																			<td>");
      out.print( aData[8] );
      out.write("</td>\r\n");
      out.write("																		</tr>	\r\n");
      out.write("																	</tbody>\r\n");
      out.write("																</table>\r\n");
      out.write("															</div>\r\n");
      out.write("														</div>\r\n");
      out.write("														\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("	\r\n");
      out.write("															<div class=\"col-xs-12 pbot30_acta\">\r\n");
      out.write("																<p class=\"subtitle1\">LISTA DE RESOLUCIONES</p>\r\n");
      out.write("																						<span class=\"glyphicon glyphicon-info-sign\" aria-hidden=\"true\"></span> No hay resoluciones para el acta seleccionada\r\n");
      out.write("																					<div id=\"page-wrap\">\r\n");
      out.write("																						<div class=\"col-md-12 resolu\">\r\n");
      out.write("																						</div>\r\n");
      out.write("																					</div>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"col-xs-12\">\r\n");
      out.write("																<p class=\"subtitle1\">INFORMACIÓN DEL ACTA ELECTORAL</p>\r\n");
      out.write("																<div id=\"page-wrap\" class=\"cont-tabla1\">\r\n");
      out.write("																	<table class=\"table06\">\r\n");
      out.write("																		<tbody>\r\n");
      out.write("																		<tr class=\"titulo_tabla\">\r\n");
      out.write("																			<td colspan=\"2\">Organización política</td>\r\n");
      out.write("																			<td>Total de Votos</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																																																															<tr>\r\n");
      out.write("																		<td>PERUANOS POR EL KAMBIO</td>\r\n");
      out.write("																		<td><img width=\"40px\" height=\"40px\" src=\"images/simbolo_pkk.jpg\"></td>\r\n");
      out.write("																		<td>\r\n");
      out.write("																				");
      out.print( aData[11] );
      out.write(" \r\n");
      out.write("																		</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																																																																							<tr>\r\n");
      out.write("																		<td>FUERZA POPULAR</td>\r\n");
      out.write("																		<td><img width=\"40px\" height=\"40px\" src=\"images/simbolo_keyko.jpg\"></td>\r\n");
      out.write("																		<td>\r\n");
      out.write("																				");
      out.print( aData[12] );
      out.write("\r\n");
      out.write("																		</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		\r\n");
      out.write("																		<tr>\r\n");
      out.write("																		<td colspan=\"2\">VOTOS EN BLANCO</td>\r\n");
      out.write("																		<td>\r\n");
      out.write("																				");
      out.print( aData[13] );
      out.write("\r\n");
      out.write("																		</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		\r\n");
      out.write("																		<tr>\r\n");
      out.write("																		<td colspan=\"2\">VOTOS NULOS</td>\r\n");
      out.write("																		<td>\r\n");
      out.write("																		  		");
      out.print( aData[14] );
      out.write("\r\n");
      out.write("																		</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		\r\n");
      out.write("																		<tr>\r\n");
      out.write("																		<td colspan=\"2\">VOTOS IMPUGNADOS</td>\r\n");
      out.write("																		<td>\r\n");
      out.write("																		  		");
      out.print( aData[15] );
      out.write("\r\n");
      out.write("																		</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		\r\n");
      out.write("																		<tr>\r\n");
      out.write("																		<td colspan=\"2\">TOTAL DE  VOTOS EMITIDOS</td>\r\n");
      out.write("																		<td>\r\n");
      out.write("																		 		");
      out.print( aData[10] );
      out.write(" \r\n");
      out.write("																	  	</td>\r\n");
      out.write("																		</tr>\r\n");
      out.write("																		</tbody>\r\n");
      out.write("																	</table>\r\n");
      out.write("																	");
 } 
      out.write("\r\n");
      out.write("																</div>\r\n");
      out.write("															</div>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>				\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						 </div>\r\n");
      out.write("						 ");
 } 
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("		      </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("          <br></br>\r\n");
      out.write("       </div>\r\n");
      out.write("   </section>\r\n");
      out.write("</div>\r\n");
      out.write("<br></br>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write(" <footer class=\"footer-inside\">\r\n");
      out.write("      <div class=\"container \">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("	   <div class=\"col-md-12 direc01\">\r\n");
      out.write("		   <span>CONTÁCTENOS</span>\r\n");
      out.write("		   <p>Jr. Washington 1894, Cercado de Lima </p>\r\n");
      out.write("		   <p>Correo electrónico: <a href=\"mailto:informes@onpe.gob.pe\">informes@onpe.gob.pe</a></p>\r\n");
      out.write("		   <p>Central Telefónica: 417 - 0630 / Lunes a Viernes 08:30 - 16:30 hrs</p>\r\n");
      out.write("	   </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
